//tealium universal tag - utag.11 ut4.0.202412100645, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}
if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1};u.initialized=false;u.map={"_sm_11_1":"container","_sm_11_2":"moduleHost,configHost","_sm_11_3":"siteKey"};u.extend=[function(a,b){try{b['_sm_11_1']=(b.hasOwnProperty('site_environment')&&b.site_environment==='prd--default')?'live':'draft';}catch(e){utag.DB(e);}
try{b['_sm_11_2']="ucm-eu.verint-cdn.com";}catch(e){utag.DB(e);}
try{b['_sm_11_3']="next-bahn-de";}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"container":"draft"
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
window.teal=window.teal||{};window.teal.unifiedSDKStarted=true;const containerCookie=document.cookie.split("; ").find((row)=>row.startsWith("uws_container_override="));const containerValue=containerCookie&&JSON.parse(decodeURIComponent(containerCookie.split("=")[1]));const config={container:containerValue||u.data.container,loadTime:Date.now()};for(let key in u.data){if(key!=='container'&&key!=='config'){config[key]=u.data[key];}}
const readyCallbacks=[];window.uwsReady=(callback)=>(readyCallbacks.push(callback));const sdkPath='//'+config.moduleHost+'/files/sites/'+config.siteKey+'/'+config.container+'/sdk.js';var verintLoader=function(src,cb){var scr=document.createElement("script");scr.type="module";scr.async=true;scr.charset="utf-8";scr.src=src;if(scr.addEventListener){scr.addEventListener("load",function(){cb()},false);var firstScr=document.getElementsByTagName('script')[0];firstScr.parentNode.insertBefore(scr,firstScr);}}
u.loader_cb=function(){u.initialized=true;if(window.unifiedSDK){window.unifiedSDK.start(config,readyCallbacks)}
};if(!u.initialized){verintLoader(sdkPath,u.loader_cb);}
}};utag.o[loader].loader.LOAD(id);})("11","bahntms.next-main");}catch(error){utag.DB(error);}
