//tealium universal tag - utag.12 ut4.0.202412100645, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}
if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={"link_name":"mafoEvent"};u.extend=[function(a,b){try{if(1){if(a==='link'){const QSI_previousInformation={};if(window.teal.storageAvailable('sessionStorage')&&b.click_name&&b.click_name==="Prozess abbrechen"){const addItemIfExists=(key,val)=>{if(val){QSI_previousInformation[key]=val;}}
addItemIfExists('previousPage',b.page_name);addItemIfExists('searchAnzahlErwachsene',b.search_anzahlErwachsene);addItemIfExists('searchAnzahlKinder',b.search_anzahlKinder);addItemIfExists('searchAnzahlReisende',b.search_anzahlReisende);addItemIfExists('searchAttributeClass',b.search_attribute_class);addItemIfExists('searchStartName',b.search_start_name);addItemIfExists('searchDestinationName',b.search_destination_name);addItemIfExists('searchAttributeShowFastestConnections',b.search_attribute_showFastestConnections);addItemIfExists('searchNurReservierung',b.search_nurReservierung);addItemIfExists('searchAttributeOutwardDateTime',b.search_attribute_outwardDateTime);addItemIfExists('selectedConnectionHinfahrtCarrier',b.selectedConnectionHinfahrt_carrier);addItemIfExists('selectedConnectionHinfahrtCapacityShortText',b.selectedConnectionHinfahrt_capacityShortText);addItemIfExists('selectedConnectionHinfahrtCountTransfers',b.selectedConnectionHinfahrt_countTransfers);if(window.teal.checkArray(b.selectedOffers_products_price_price))addItemIfExists('selectedOffersProductsPricePrice',b.selectedOffers_products_price_price[0]);if(window.teal.checkArray(b.selectedOffers_products_info_name))addItemIfExists('selectedOffersProductsInfoName',b.selectedOffers_products_info_name[0]);addItemIfExists('userLoginStatus',b.user_loginStatus);if(window.teal.checkArray(b.selectedPayment_paymentOptions_paymentMethod))addItemIfExists('selectedPaymentPaymentOptionsPaymentMethod',b.selectedPayment_paymentOptions_paymentMethod.join(';'));addItemIfExists('pageRendering',b.page_rendering);const jsonObjectQSI_previousInformation=JSON.stringify(QSI_previousInformation);sessionStorage.setItem('QSI_previousInformations',jsonObjectQSI_previousInformation);}}else if(a==='view'){if(window.teal.storageAvailable('sessionStorage')&&sessionStorage.getItem('QSI_previousInformations')){const previousInformations=sessionStorage.getItem('QSI_previousInformations');window.utag_data.mafo.previousPageInformation=JSON.parse(previousInformations);sessionStorage.removeItem('QSI_previousInformations');}
if(window.teal.checkArray(b.selectedOffers_products_info_name)&&window.teal.storageAvailable('sessionStorage')&&sessionStorage.getItem('vuex')){var testJson=function(a){try{JSON.parse(a);}catch(err){return false;}
return true;};if(testJson(sessionStorage.getItem('vuex'))){var vuexData=teal.flattenObject(JSON.parse(sessionStorage.getItem('vuex')));if(vuexData.fahrplanAngebotState_selectedAngebote_angebotsIdHinfahrt){utag_data.mafo.angebotsIdHinfahrt=vuexData.fahrplanAngebotState_selectedAngebote_angebotsIdHinfahrt;}
if(vuexData.fahrplanAngebotState_selectedAngebote_angebotsIdRueckfahrt){utag_data.mafo.angebotsIdRueckfahrt=vuexData.fahrplanAngebotState_selectedAngebote_angebotsIdHinfahrt;}}}
if(typeof b.reservationSelected!=='undefined'){window.utag_data.mafo.reservationSelected=b.reservationSelected;}
var passengers=window.teal.summarizeArray(b.search_attribute_passengers_type,'>',';');if(passengers){window.utag_data.mafo.passengers=passengers;}
if(window.teal.checkArray(b.selectedPayment_paymentOptions_paymentMethod)){window.utag_data.mafo.selectedPayment=b.selectedPayment_paymentOptions_paymentMethod.join('>');}
if(b.currentModel&&b.currentModel.search&&b.currentModel.search.attribute&&window.teal.checkArray(b.currentModel.search.attribute.passengers)){var source=b.currentModel.search.attribute.passengers;var count={}
var result='';source.map(function(el){var passengerString=''
passengerString+=((el.type)?el.type:'NA')+'>';if(el.discounts){passengerString+=el.discounts.map(function(discount){return((discount.abbreviation)?discount.abbreviation:'NA')+'_'+((typeof discount.class!=='undefined')?discount.class:'NA');}).join(',')}else{passengerString+='NA_NA'}
if(count[passengerString]){count[passengerString]+=1;}else{count[passengerString]=1;}})
for(var prop in count){if(result)result+=';';result+=count[prop]+'>'+prop;}
window.utag_data.mafo.discountCards=result;}
if(b.currentModel&&window.teal.checkArray(b.currentModel.selectedOffers)){var result=b.currentModel.selectedOffers.map(function(offer){var source=offer.products||[];return source.map(function(el){var productString=''
productString+=((el.info&&el.info.name)?el.info.name:'NA')+'>';productString+=((el.direction)?el.direction:'NA')+'>';productString+=((el.class)?(el.class+'.Kl'):'NA')+'>';productString+=((el.price&&typeof el.price.price!=='undefined')?el.price.price:'NA');return productString;}).join(';');}).join(';');if(result){window.utag_data.mafo.selectedProducts=result;}}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(a==='link'&&u.data.mafoEvent){window._qsie=window._qsie||[];window._qsie.push(u.data.mafoEvent);if(typeof window.QSI==='object'&&window.QSI.hasOwnProperty('EventTracker')&&typeof window.QSI.EventTracker.storeCounts==='function'){window.QSI.EventTracker.storeCounts();}}
u.loader_cb=function(){u.initialized=true;};if(a==='view'){if(!u.initialized){!function(){try{new function(t,e,n,i){this.get=function(t){t+="=";for(var e=document.cookie.split(";"),n=0,i=e.length;n<i;n++){for(var r=e[n];" "==r.charAt(0);)r=r.substring(1,r.length);if(0==r.indexOf(t))return r.substring(t.length,r.length)}
return null},this.set=function(t,e){var n="";(n=new Date).setTime(n.getTime()+6048e5),n="; expires="+n.toGMTString(),document.cookie=t+"="+e+n+"; path=/; "},this.check=function(){var i=this.get(n);if(i)i=i.split(":");else{if(100==t)return!0;"v"==e&&(t=Math.random()>=t/100?0:100),i=[e,t,0],this.set(n,i.join(":"))}
var r=i[1];if(100==r)return!0;switch(i[0]){case"v":return!1;case"r":return r=i[2]%Math.floor(100/r),i[2]++,this.set(n,i.join(":")),!r}
return!0},this.go=function(){if(this.check()){u.loader({"type":"script","src":i+"&t="+(new Date).getTime(),"cb":u.loader_cb,"loc":"script","id":'utag_12'});}},this.start=function(){try{this.go()}catch(t){}}}(100,"r","QSI_S_ZN_0lxkzEthotizcTX","https://zn0lxkzethotizctx-bahn.siteintercept.qualtrics.com/SIE/?Q_ZID=ZN_0lxkzEthotizcTX&Q_LOC="+encodeURIComponent(window.location.href)).start()}catch(t){}}();}else{if(QSI&&QSI.API){QSI.API.unload();QSI.API.load();QSI.API.run();}}}
}};utag.o[loader].loader.LOAD(id);})("12","bahntms.next-main");}catch(error){utag.DB(error);}
