//tealium universal tag - utag.30 ut4.0.202412100645, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.scriptrequested=false;u.escape=window.encodeURIComponent||window.escape;u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}
else if(typeof object[key]==='object'){u.clearEmptyKeys(object[key]);}}
return object;};u.map={"adftrackingId":"campaignid","_sm_30_2":"page_name","adfStep":"step","user_customerType":"order.sv100","user_customerClass":"order.sv101","user_loginStatus":"order.sv102","user_region":"order.sv103","searchStartNoPoi":"order.sv104","searchDestNoPoi":"order.sv105","search_attribute_class":"order.sv106","adfPassengers":"order.sv107","search_anzahlReisende":"order.sv108","search_attribute_passengers_age":"order.sv109","cartPrice_price":"order.sv112","_sm_30_15":"order.sv113","adfProductIds":"product.sv114","user_city":"order.sv115","user_country":"order.sv116","user_bahnCardStatus":"order.sv117","searchStartExtIdNoPoi":"order.sv118","searchDestExtIdNoPoi":"order.sv119","search_nurReservierung":"order.sv120","selectedVehicles":"order.sv121","selectedProductClassSum_ship":"order.sv122","selectedProductClassSum_ice":"order.sv123","selectedProductClassSum_ecic":"order.sv124","selectedProductClassSum_ir":"order.sv125","selectedProductClassSum_regional":"order.sv126","selectedProductClassSum_s":"order.sv127","selectedProductClassSum_bus":"order.sv128","selectedProductClassSum_u":"order.sv129","selectedProductClassSum_tram":"order.sv130","selectedProductClassSum_av":"order.sv131","selectedCountTransfersSum":"order.sv132","search_attribute_outwardDateTime":"order.sv135","search_attribute_outwardDateTimeRueckfahrt":"order.sv136"};u.extend=[function(a,b){try{b['_sm_30_15']=(window.teal.checkArray(b._cprodname)&&window.teal.checkArray(b.selectedOffers_products_info_name))?b._cprodname:undefined;}catch(e){utag.DB(e);}
try{b['_sm_30_2']='{'+(document.location.hostname||'')+'}|{'+(b.page_channel||b.page_section||'')+'}|{'+(b.page_name||'')+'}';}catch(e){utag.DB(e);}},function(a,b){try{if(1){b.adftrackingId=(b.site_environment&&b.site_environment==='prd--default')?'2583931':'648957';let adfServer='https://'+((b['dom.domain'])?(b['dom.domain']+'/af'):'www.bahn.de/af');b.adfBaseUrl=adfServer+'/v2/sitetracking/'+b.adftrackingId+'/trackingpoints/';b.adfStep=1;if(window.teal.checkArray(b.selectedOffers_products_info_id)&&window.teal.checkArray(b.selectedOffers_products_type)){b.adfStep=2;let adfProductIds=b.selectedOffers_products_info_id;b.adfProductIds=[...b.selectedOffers_products_info_id];if(b.searchStartExtIdNoPoi&&b.searchDestExtIdNoPoi&&adfProductIds.length===b.selectedOffers_products_type.length&&(b.selectedOffers_products_type.indexOf('Fahrkarte')>-1||b.selectedOffers_products_type.indexOf('Reservierung')>-1)){let newProductId=b.searchStartExtIdNoPoi+'_'+b.searchDestExtIdNoPoi;let searchString=(b.selectedOffers_products_type.indexOf('Fahrkarte')>-1)?'Fahrkarte':'Reservierung';for(let i=0;i<=adfProductIds.length;i++){if(b.selectedOffers_products_type[i]===searchString){adfProductIds[i]=newProductId;break;}}
b._cprod=adfProductIds;}}else{b._cprod=[];b._cprodname=[];b._cquan=[];b._cprice=[];if(b.searchStartExtIdNoPoi&&b.searchDestExtIdNoPoi){b._cprod=[(b.searchStartExtIdNoPoi+'_'+b.searchDestExtIdNoPoi)];}}
if(b.transactionOrderNumberEncrypted&&window.teal.checkArray(b._cprodname)){b.adfStep=3;}
if(b.currentModel&&b.currentModel.search&&b.currentModel.search.attribute&&b.currentModel.search.attribute.passengers){let source=b.currentModel.search.attribute.passengers;b.adfPassengers=source.map((el)=>{let passengerString=''
passengerString+=((el.type)?el.type:'NA')+'_';if(el.discounts){passengerString+=el.discounts.map((discount)=>{return((discount.abbreviation)?discount.abbreviation:'NA')+' '+((typeof discount.class!=='undefined')?discount.class:'NA');}).join('>')}else{passengerString+='NA NA'}
return passengerString;}).join(',');}
if(window.teal.checkArray(b.selectedConnectionHinfahrt_vehicles)){let selectedVehiclesArr=(window.teal.checkArray(b.selectedConnectionRueckfahrt_vehicles))?b.selectedConnectionHinfahrt_vehicles.concat(b.selectedConnectionRueckfahrt_vehicles):b.selectedConnectionHinfahrt_vehicles;b.selectedVehicles=selectedVehiclesArr.join(',');}
let productClasses=['av','bus','ecic','ice','ir','regional','s','ship','tram','u']
productClasses.forEach((productClass)=>{if(b['selectedConnectionHinfahrt_productClass_'+productClass]){b['selectedProductClassSum_'+productClass]=((+b['selectedConnectionHinfahrt_productClass_'+productClass])+
((b['selectedConnectionRueckfahrt_productClass_'+productClass])?+b['selectedConnectionRueckfahrt_productClass_'+productClass]:0));}});if(b.selectedConnectionHinfahrt_countTransfers){b.selectedCountTransfersSum=((+b.selectedConnectionHinfahrt_countTransfers)+
((b.selectedConnectionRueckfahrt_countTransfers)?+b.selectedConnectionRueckfahrt_countTransfers:0));}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:30");utag.DB(b);var c,d,e,f,prop,i,customvar;u.data={"base_url":"//a1.adform.net/serving/scripts/trackpoint/async/","campaignid":"648957","page_name":"","divider":"|","adform_tracking_object":{},"step":"","customer_agegroup":"","customer_gender":"","order_id":"","order_subtotal":"","order_currency":"","customer_country":"","product_id":[],"product_name":[],"product_brand":[],"product_category":[],"product_category_id":[],"product_quantity":[],"product_unit_price":[],"product_weight":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:30:EXTENSIONS");utag.DB(b);for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:30:MAPPINGS");utag.DB(u.data);window._adftrack=u.typeOf(window._adftrack)==="array"?window._adftrack:(window._adftrack?[window._adftrack]:[]);u.data.adform_tracking_object.pm=u.escape(u.data.campaignid);u.data.adform_tracking_object.divider=u.escape(u.data.divider);if(u.data.page_name){u.data.adform_tracking_object.pagename=u.escape(u.data.page_name);}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";u.data.customer_country=u.data.customer_country||b._ccountry||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.typeOf(u.data.product_category_id)==="string"){u.data.product_category_id=u.data.product_category_id.split(",");}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(u.typeOf(u.data.product_weight)==="string"){u.data.product_weight=u.data.product_weight.split(",");}
u.data.step=u.data.step||(b._corder?"3":"1");if(!u.data.campaignid){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
u.data.adform_tracking_object.order={};u.data.adform_tracking_object.order.sales=u.data.order_subtotal||"";u.data.adform_tracking_object.order.currency=u.data.order_currency||"";u.data.adform_tracking_object.order.basketsize=u.data.product_id.length||"";u.data.adform_tracking_object.order.country=u.data.customer_country||"";u.data.adform_tracking_object.order.orderid=u.data.order_id||"";u.data.adform_tracking_object.order.orderstatus=u.data.order_status||"";u.data.adform_tracking_object.order.gender=u.data.customer_gender||"";u.data.adform_tracking_object.order.agegroup=u.data.customer_agegroup||"";u.data.adform_tracking_object.order.itms="";if(u.data.product_id.length>0){u.data.adform_tracking_object.order.itms=[];u.data.product_id.forEach(function(productId,i){var product={};product.categoryname=u.data.product_category[i]||"";product.productid=productId;product.productname=u.data.product_name[i]||"";product.productcount=u.data.product_quantity[i]||"";product.productsales=u.data.product_unit_price[i]||"";product.categoryid=u.data.product_category_id[i]||"";product.weight=u.data.product_weight[i]||1;product.step=u.data.step;u.data.adform_tracking_object.order.itms.push(product);});}
u.data.adform_tracking_object.order=u.clearEmptyKeys(u.data.adform_tracking_object.order);for(prop in u.data){if(u.data.hasOwnProperty(prop)){customvar=prop.split(".")[1];if(/^order\.(sv|var)/.test(prop)){u.data.adform_tracking_object.order[customvar]=""+(u.data[prop]);}else if(/^product\.(sv|var)/.test(prop)){if((u.data[prop]instanceof Array)&&u.data[prop].length===u.data.product_id.length){for(i=0;i<u.data.product_id.length;i++){u.data.adform_tracking_object.order.itms[i][customvar]=""+(u.data[prop][i]);}}}}}
if(!u.scriptrequested){u.scriptrequested=true;window._adftrack.push(u.data.adform_tracking_object);u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":"utag_30","attrs":{}});}else{if(a==="view"){window.adf.async.TrackOne(u.data.adform_tracking_object);}else{window.adf.ClickTrack(this,u.data.campaignid,u.data.page_name,u.data.adform_tracking_object.order);}}
utag.DB("send:30:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("30","bahntms.next-main"));}catch(error){utag.DB(error);}
